#spring:
#  application:
#    name: ms-auth-service
#  profiles:
#    active: development
#  config:
#    import: optional:configserver:http://root:s3cr3t@localhost:7070

#jwt:
#  secret: secret
server:
  port: ${PORT:${SERVER_PORT:0}}
spring:
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/msauth
    username: root
    password:
eureka:
  client:
    serviceUrl:

      defaultZone: ${EUREKA_URI:http://localhost:8090/eureka}
  instance:

    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}