server:
    port: 7070
spring:
    application:
        name: config-server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/EnriqueMV18/MS-CICLOV.git
                    search-paths: config-data
                    username: EnriqueMV18
                    password: enriquemv15
                    default-label: ms-config-server
    security:
        user:
            name: root
            password: s3cr3t
